socialPluginConfig = {
		homeURL: 'http://localhost:8080/CamZone/',
		profilepicBaseURL: 'http://localhost:8080/SocialPlugin/',
		baseURL: 'http://localhost:8080/SocialPlugin/rest/user/',
		reactionBaseURL: 'http://localhost:8080/SocialPlugin/rest/plugins/8001/',
		firstBadgeURL: 'http://localhost:8080/camzone-admin/LeaderBadges/first_leader.jpg',
		secondBadgeURL: 'http://localhost:8080/camzone-admin/LeaderBadges/second_leader.jpg',
		thirdBadgeURL: 'http://localhost:8080/camzone-admin/LeaderBadges/third_leader.jpg',
		notificationURL : 'http://localhost:8080/SocialPlugin/rest/user/getNotifications', 
		getWidgetsUrl: 'http://localhost:8080/SocialPlugin/rest/widgets/fetchAllWidgets', 
		getPageWidgetsUrl :'http://localhost:8080/SocialPlugin/rest/widgets/getPageWidgets', 
		getProductsUrl :'http://localhost:8080/SocialPlugin/rest/products/getAllProducts',
		getProductsByCategoryUrl:'http://localhost:8080/SocialPlugin/rest/products/getProductsByCategory', 
		getProductViewedUrl:'http://localhost:8080/SocialPlugin/rest/products/productViewed',
		getProductsInCart : 'http://localhost:8080/SocialPlugin/rest/products/itemsInCart',
		getAddToCartUrl : 'http://localhost:8080/SocialPlugin/rest/products/addToCart',
		getproductByNameUrl:'http://localhost:8080/SocialPlugin/rest/products/getProductByName',
		getproductByIdUrl:'http://localhost:8080/SocialPlugin/rest/products/getProductById',
		getDeleteFromCartUrl :'http://localhost:8080/SocialPlugin/rest/products/deleteFromCart',
		getRecommendedProductsUrl:'http://10.150.10.205:8010/sparkrest/rest/person/',
		getRecommendedProductsFromBHUrl : 'http://localhost:8080/SocialPlugin/rest/products/itemsFromBH',
		getproductsViewedRecentlyUrl:'http://localhost:8080/SocialPlugin/rest/products/productsViewedRecently',
		getCartingRecommendationUrl :'http://localhost:8080/SocialPlugin/rest/products/productsInOthersCart'
};
